name: Yaml delete
description: Deletes a specific object in a yaml file.

inputs:
  yaml_file:
    description: Path to the yaml file to modify
    required: true
  yaml_path:
    description: Where the target value is found
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Install yamlpath
      shell: bash
      run: pip install yamlpath

      # The extended bash script ignore errors where the path does not exists, otherwise it returns the 
      # default exitcode and stderr
    - name: Delete yaml value
      shell: bash
      run: |
        ERR_IGNORE='Required YAML Path does not match any nodes'
        ERR_OUT=$(yaml-set --delete --change  ${{ inputs.yaml_path }} ${{ inputs.yaml_file }} 2>&1 >/dev/null) && RETURN_CODE=$? || RETURN_CODE=$?

        if [[ ${RETURN_CODE} == 0 ]] || [[ ${ERR_OUT} = *"${ERR_IGNORE}"* ]]
        then
            exit 0
        else
            echo ${ERR_OUT} >&2
            exit ${RETURN_CODE}
        fi
