name: Run lint-flake8 using pipenv

on:
  workflow_call:
    inputs:
      python_version:
        description: The version of python to use
        type: string
        required: true
      exclude:
        description: Paths to exclude when linting, defaults to excluding './src/migrations/versions'
        type: string
        default: ./src/migrations/versions
        required: false
      ignore_lint_error:
        description: Whether or not to ignore linting errors.
        type: boolean
        default: false
        required: false

jobs:
  py_lint:
    name: Lint python code
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.ignore_lint_error }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python and dependencies
        uses: MartinSchmidt/ReusableWorkflow/.github/actions/python_pipenv_install_dependencies@main
        with: 
          python_version: ${{ inputs.python_version }}

      - name: Analyzing the code with flake8
        shell: bash
        run: pipenv run lint-flake8 --exclude ${{ inputs.exclude }}
