name: Run lint-flake8 using pipenv

on:
  workflow_call:
    inputs:
      python_version:
        description: The version of python to use
        type: string
        required: true

jobs:
  py_lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Analyzing the code with flake8
        shell: bash
        run: echo "hello ${{ inputs.python_version }}"
